[project]
name = "get-qqchat"
version = "0.1.0"
description = "一个获取 QQ 聊天记录的 CLI"
readme = "README.md"
authors = [
    { name = "luludesuwa", email = "lulu_desuwa@163.com" }
]
requires-python = ">=3.12"


[project.scripts]
get-qqchat = "get_qqchat.cli:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
