[project]
name = "get-qqchat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "luludesuwa", email = "lulu_desuwa@163.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
get-qqchat = "get_qqchat:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
